name: Unit Tests

on:
  workflow_call:

jobs:
  test-nix:
    name: Test on *NIX
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "ubuntu-22.04"
          - "macos-13"
        dotnet:
          - "net6.0"
          - "net7.0"
          - "net8.0"
          - "net9.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      id: setup-step
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          9.0.x

    - uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet }} --no-restore --verbosity normal "tests\Mindee.UnitTests"

  test-windows:
    name: Test on Windows
    timeout-minutes: 30
    strategy:
      matrix:
        dotnet:
          - "net472"
          - "net482"
          - "net6.0"
          - "net7.0"
          - "net8.0"
          - "net9.0"
    runs-on: "windows-2022"
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      id: setup-step
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          9.0.x

    - uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet }} --no-restore --verbosity normal "tests\Mindee.UnitTests"
