name: Automated Tests

on:
  schedule:
  - cron: '45 0 * * *'

jobs:
  codeql:
    uses: mindee/mindee-api-dotnet/.github/workflows/_codeql.yml@main
  test_code_samples:
    uses: mindee/mindee-api-dotnet/.github/workflows/_test-code-samples.yml@main
    secrets: inherit
