name: .NET 4.7.2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore "src"
    - name: Build
      run: dotnet build "src" --configuration Release --no-restore -f net472

  test:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET Core SDK '6.0.x'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test "tests\Mindee.UnitTests" -f net472 --no-restore --verbosity normal
