#
# Run unit tests.
#
name: Tests

on:
  - push

jobs:
  test-nix:
    name: Run Tests on *nix
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
        dotnet-version:
          - "net6.0"
          - "net7.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet-version }} --no-restore --verbosity normal "tests\Mindee.UnitTests"
    
    - name: Prepare samples code
      run: |
        mkdir "${{ github.workspace }}/localNuget"
        dotnet nuget add source "${{ github.workspace }}/localNuget" -n "NugetLocal"
        dotnet nuget list source
        dotnet pack "src/Mindee" --version-suffix "test" -p:TargetFrameworks=${{ matrix.dotnet-version }} --output nuget
        cd nuget
        dotnet nuget push *.nupkg --source "NugetLocal"
        dotnet tool install -g dotnet-script

    - name: Test samples code
      run: |
        cd samples
        cat base.csx receiptv4.cs > receiptv4.csx
        sed 's/MyApiKey/${{ secrets.MINDEE_API_KEY }}/' <receiptv4.csx >receiptv4_.csx
        sed 's/MyFilePath/..\/tests\/resources\/receipt\/receipt-with-tip.jpg/' <receiptv4_.csx >receiptv4.csx
        dotnet script receiptv4.csx

  test-windows:
    name: Run Tests on Windows
    timeout-minutes: 30
    strategy:
      matrix:
        dotnet-version:
          - "net472"
          - "net6.0"
          - "net7.0"
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet-version }} --no-restore --verbosity normal "tests\Mindee.UnitTests"

    - name: Prepare samples code
      run: |
        mkdir "${{ github.workspace }}/localNuget"
        dotnet nuget add source "${{ github.workspace }}/localNuget" -n "NugetLocal"
        dotnet nuget list source
        dotnet pack "src/Mindee" --version-suffix "test" -p:TargetFrameworks=${{ matrix.dotnet-version }} --output nuget
        cd nuget
        dotnet nuget push *.nupkg --source "NugetLocal"
        dotnet tool install -g dotnet-script

    - name: Test samples code
      run: |
        cd samples
        cat base.csx receiptv4.cs > receiptv4.csx
        sed 's/MyApiKey/${{ secrets.MINDEE_API_KEY }}/' <receiptv4.csx >receiptv4_.csx
        sed 's/MyFilePath/..\/tests\/Resources\/receipt\/receipt-with-tip.jpg/' <receiptv4_.csx >receiptv4.csx
        dotnet script receiptv4.csx
