name: .NET 4.7.2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    - name: Restore Packages
      run: nuget restore "src/Mindee.sln"
    - name: Build Solution
      run: |
        msbuild.exe "src/Mindee.sln" /p:platform="Any CPU" /p:configuration="Release" /p:TargetFramework=net472

  test:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET Core SDK '6.0.x'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test "tests\Mindee.UnitTests" -f net472 --no-restore --verbosity normal
