name: Integration Tests

on:
  pull_request:
  schedule:
    - cron:  '41 04 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Mindee__ApiKey: ${{ secrets.MINDEE_API_KEY }}

jobs:
  test-nix:
    name: Test on *NIX
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
        dotnet-version:
          - "net6.0"
          - "net7.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet-version }} --verbosity normal "tests\Mindee.IntegrationTests"

  test-windows:
    name: Test on Windows
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "windows-latest"
        dotnet-version:
          - "net472"
          - "net482"
          - "net6.0"
          - "net7.0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build and test
        run: |
          dotnet test -f ${{ matrix.dotnet-version }} --verbosity normal "tests\Mindee.IntegrationTests"
