name: Non regression tests

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '41 04 * * *'

jobs:
  test-nix:
    name: Run Tests on *nix
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        dotnet-version:
          - "net7.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Define env variables
      run: |
        set Mindee__ApiKey=${{ secrets.MINDEE_API_KEY }}

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet-version }} --no-restore --verbosity normal "tests\Mindee.IntegrationTests"
