#
# Non regression tests.
#
name: Non regression tests

on:
  push:
    branches:
      - main
      - 141-cannot-install-on-net-48-project
  schedule:
    - cron:  '41 04 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Mindee__ApiKey: ${{ secrets.MINDEE_API_KEY }}

jobs:
  test-nix:
    name: Run Tests on *nix
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        dotnet-version:
          - "net7.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet-version }} --verbosity normal "tests\Mindee.IntegrationTests"

  test-windows:
    name: Run Tests on Windows
    timeout-minutes: 30
    strategy:
      matrix:
        dotnet-version:
          - "net472"
          - "net48"
    runs-on: "windows-latest"
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build and test
      run: |
        dotnet test -f ${{ matrix.dotnet-version }} --verbosity normal "tests\Mindee.IntegrationTests"
