# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Publish documentation (API reference)

on:  
  release:
    types: [ published ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET SDK '7.0.x'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: dotnet build "src" --configuration Release -o "./build"
      - name: Install MdDocs
        run: dotnet tool install --global Grynwald.MdDocs
      - name: Setup .NET SDK '7.0.x'
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
      - name: Generate documentations
        run: mddocs apireference --assembly './build/Mindee.dll' --outdir ./docs/api-reference
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/api-reference
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
