#
# Publish releases to Nuget
#
name: Publish Release

on:
  release:
    types: [ published ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Publish release to Nuget
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore "src/Mindee"
      - name: Build
        run: dotnet build "src/Mindee" --configuration Release --no-restore
      - name: Pack
        run: dotnet pack "src/Mindee" -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --no-build --output nuget
      - name: Publish NuGet packages to NuGet
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source "nuget.org"
