name: Publish Documentation

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build "src" --configuration Release

      - name: Install MdDocs
        run: dotnet tool install --global Grynwald.MdDocs

      - name: Generate documentation
        run: mddocs apireference --assemblies 'src/Mindee/bin/Release/net7.0/Mindee.dll' --outdir ./docs/api_reference

      - name: Copy Samples
        run: cp -r ./docs/code_samples ./docs/api_reference/Mindee

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/api_reference/Mindee
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: /home/runner/work/mindee-api-dotnet/mindee-api-dotnet/_site

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
