#
# Run sample codes tests.
#
name: Test samples codes

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '23 23 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        dotnet-version:
          - "net6.0"
          - "net7.0"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Install dependencies
      run: |
        dotnet restore

    - name: Build and test
      run: |
        dotnet build -f ${{ matrix.dotnet-version }} --no-restore --verbosity normal
    
    - name: Prepare for samples code
      run: |
        mkdir "${{ github.workspace }}/localNuget"
        dotnet nuget add source "${{ github.workspace }}/localNuget" -n "NugetLocal"
        dotnet nuget list source
        dotnet pack "src/Mindee" --version-suffix "test" -p:TargetFrameworks=${{ matrix.dotnet-version }} --output nuget
        cd nuget
        dotnet nuget push *.nupkg --source "NugetLocal"
        dotnet tool install -g dotnet-script

    - name: Tests sample code
      run: |
        ./test_sample_code.sh ${{ secrets.MINDEE_API_KEY }}
